import { db, gdOffersTable } from "@workspace/db";

const offers = [
  {
    distribuidora: "Equatorial GO",
    estado: "Goiás",
    uf: "GO",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "15% a 22%",
    descontoFixoRaw: "18%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 22.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "25%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Até 30%",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 25.0,
    discountMax: 25.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "RGE",
    estado: "Rio Grande do Sul",
    uf: "RS",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "15% a 22%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 22.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "COPEL",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "12% a 22%",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "500-1000 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 12.0,
    discountMax: 22.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "CELESC",
    estado: "Santa Catarina",
    uf: "SC",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Sujeito a Consulta",
    descontoVariavelRaw: "10% a 20%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 20.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "CEEE Equatorial",
    estado: "Rio Grande do Sul",
    uf: "RS",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Sujeito a Consulta",
    descontoVariavelRaw: "10% a 20%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 20.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Equatorial GO",
    estado: "Goiás",
    uf: "GO",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo A",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Sujeito a Consulta",
    descontoVariavelRaw: "5% a 22%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "-",
    fidelidade: "Não",
    tipoCliente: "Grupo A",
    observacoes: "",
    discountMin: 5.0,
    discountMax: 22.0,
    ticketMinimoKwh: null,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo A",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "5% a 22%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "-",
    fidelidade: "Não",
    tipoCliente: "Grupo A",
    observacoes: "",
    discountMin: 5.0,
    discountMax: 22.0,
    ticketMinimoKwh: null,
  },
  {
    distribuidora: "RGE",
    estado: "Rio Grande do Sul",
    uf: "RS",
    regiao: "Sul",
    grupoTarifario: "Grupo A",
    comercializadora: "LUDFOR ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "5% a 22%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "-",
    fidelidade: "Não",
    tipoCliente: "Grupo A",
    observacoes: "",
    discountMin: 5.0,
    discountMax: 22.0,
    ticketMinimoKwh: null,
  },
  {
    distribuidora: "CPFL Paulista",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Sem Disponibilidade",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "19%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 19.0,
    discountMax: 19.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "21%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 21.0,
    discountMax: 21.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "CPFL Santa Cruz",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste/Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "16%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 16.0,
    discountMax: 16.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "CPFL Santa Cruz",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sudeste/Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "16%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 16.0,
    discountMax: 16.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "CPFL Santa Cruz",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste/Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "16%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 16.0,
    discountMax: 16.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Energisa Mato Grosso",
    estado: "Mato Grosso",
    uf: "MT",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Energisa Mato Grosso do Sul",
    estado: "Mato Grosso do Sul",
    uf: "MS",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "18%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 18.0,
    discountMax: 18.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Equatorial GO",
    estado: "Goiás",
    uf: "GO",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "17%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 17.0,
    discountMax: 17.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "COELBA",
    estado: "Bahia",
    uf: "BA",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "18%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 18.0,
    discountMax: 18.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Equatorial PI",
    estado: "Piauí",
    uf: "PI",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "17%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 17.0,
    discountMax: 17.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Elektro",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "16%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 16.0,
    discountMax: 16.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "Elektro",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "16%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 16.0,
    discountMax: 16.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "COPEL",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "PRIME ENERGY",
    produto: "GD",
    status: "Sem Disponibilidade",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "500 kWh",
    fidelidade: "Não",
    tipoCliente: "Comercial",
    observacoes: "CPF vinculado a ponto comercial",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 500,
  },
  {
    distribuidora: "ENEL RJ",
    estado: "Rio de Janeiro",
    uf: "RJ",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GENIAL ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "10% a 15%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "400 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "Varia conforme bandeira tarifária",
    discountMin: 10.0,
    discountMax: 15.0,
    ticketMinimoKwh: 400,
  },
  {
    distribuidora: "LIGHT RJ",
    estado: "Rio de Janeiro",
    uf: "RJ",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GENIAL ENERGIA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "10% a 15%",
    descontoFixoRaw: "-",
    ticketMinimoRaw: "400 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "Varia conforme bandeira tarifária",
    discountMin: 10.0,
    discountMax: 15.0,
    ticketMinimoKwh: 400,
  },
  {
    distribuidora: "AMAZONAS ENERGIA",
    estado: "Amazonas",
    uf: "AM",
    regiao: "Norte",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "RGE",
    estado: "Rio Grande do Sul",
    uf: "RS",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "ELETROCAR",
    estado: "Rio Grande do Sul",
    uf: "RS",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CEEE Equatorial",
    estado: "Rio Grande do Sul",
    uf: "RS",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CELESC",
    estado: "Santa Catarina",
    uf: "SC",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "DCELT",
    estado: "Santa Catarina",
    uf: "SC",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "COPEL",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CPFL Santa Cruz",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa Sul-Sudeste",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CPFL Paulista",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CPFL Santa Cruz",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Elektro",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CPFL Piratininga",
    estado: "São Paulo",
    uf: "SP",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "8%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 8.0,
    discountMax: 8.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "ENEL RJ",
    estado: "Rio de Janeiro",
    uf: "RJ",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "12%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 12.0,
    discountMax: 12.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "LIGHT RJ",
    estado: "Rio de Janeiro",
    uf: "RJ",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Sujeito a Consulta",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa Minas Rio",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "EDP ES",
    estado: "Espírito Santo",
    uf: "ES",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "12%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 12.0,
    discountMax: 12.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa Mato Grosso do Sul",
    estado: "Mato Grosso do Sul",
    uf: "MS",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa Mato Grosso",
    estado: "Mato Grosso",
    uf: "MT",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Equatorial GO",
    estado: "Goiás",
    uf: "GO",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Neoenergia Brasília",
    estado: "Distrito Federal",
    uf: "DF",
    regiao: "Centro-Oeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "COELBA",
    estado: "Bahia",
    uf: "BA",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "20%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 20.0,
    discountMax: 20.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Neoenergia Pernambuco",
    estado: "Pernambuco",
    uf: "PE",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa PB",
    estado: "Paraíba",
    uf: "PB",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "ENEL CE",
    estado: "Ceará",
    uf: "CE",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Equatorial PI",
    estado: "Piauí",
    uf: "PI",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa SE",
    estado: "Sergipe",
    uf: "SE",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "COSERN",
    estado: "Rio Grande do Norte",
    uf: "RN",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Equatorial AL",
    estado: "Alagoas",
    uf: "AL",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Energisa TO",
    estado: "Tocantins",
    uf: "TO",
    regiao: "Norte",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Equatorial PA",
    estado: "Pará",
    uf: "PA",
    regiao: "Norte",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "Equatorial MA",
    estado: "Maranhão",
    uf: "MA",
    regiao: "Nordeste",
    grupoTarifario: "Grupo B",
    comercializadora: "GEDISA",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "300 kWh",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 300,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "ATMO",
    produto: "GD Solar",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "100 kWh",
    fidelidade: "Priorizar",
    tipoCliente: "Residencial/Comercial",
    observacoes: "Oferta com fidelidade recomendada",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: 100,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "ATMO",
    produto: "GD CGH",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "19%",
    ticketMinimoRaw: "100 kWh",
    fidelidade: "Priorizar",
    tipoCliente: "Residencial/Comercial",
    observacoes: "Oferta com fidelidade recomendada",
    discountMin: 19.0,
    discountMax: 19.0,
    ticketMinimoKwh: 100,
  },
  {
    distribuidora: "COPEL",
    estado: "Paraná",
    uf: "PR",
    regiao: "Sul",
    grupoTarifario: "Grupo B",
    comercializadora: "ATMO",
    produto: "GD Solar",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "10%",
    ticketMinimoRaw: "100 kWh",
    fidelidade: "Priorizar",
    tipoCliente: "Residencial/Comercial",
    observacoes: "Oferta com fidelidade recomendada",
    discountMin: 10.0,
    discountMax: 10.0,
    ticketMinimoKwh: 100,
  },
  {
    distribuidora: "CEMIG",
    estado: "Minas Gerais",
    uf: "MG",
    regiao: "Sudeste",
    grupoTarifario: "Grupo B",
    comercializadora: "DELANTIS",
    produto: "GD",
    status: "Disponível",
    descontoVariavelRaw: "-",
    descontoFixoRaw: "15%",
    ticketMinimoRaw: "-",
    fidelidade: "Não",
    tipoCliente: "Residencial/Comercial",
    observacoes: "",
    discountMin: 15.0,
    discountMax: 15.0,
    ticketMinimoKwh: null,
  },
] as const;

async function main() {
  await db.delete(gdOffersTable);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await db.insert(gdOffersTable).values(offers as any);
  console.log(`Seeded ${offers.length} gd_offers rows.`);
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
